//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kutuphane.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class EmanetKitaplar
    {
        public int ID { get; set; }
        [DisplayName("KÝTAP")]
        public Nullable<int> KitapId { get; set; }
        [DisplayName("KULLANICI")]
        public Nullable<int> KullaniciId { get; set; }
        [DisplayName("ALDIÐI TARÝH")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd-MM-yyyy}")]
        public Nullable<System.DateTime> AldigiTarih { get; set; }
        [DisplayName("VERECEÐÝ TARÝH")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd-MM-yyyy}")]
        public Nullable<System.DateTime> VerecegiTarih { get; set; }
        [DisplayName("VERDÝÐÝ TARÝH")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd-MM-yyyy}")]
        public Nullable<System.DateTime> VerdigiTarih { get; set; }
        [DisplayName("BORÇ")]
        [RegularExpression("[0-9.,]+", ErrorMessage = "Sadece Sayý Ýçerebilir")]
        public Nullable<decimal> Borcu { get; set; }
        [DisplayName("HASAR DURUMU")]
        public string HasarDurumu { get; set; }
        [DisplayName("TESLÝM DURUMU")]
        public Nullable<bool> TeslimDurumu { get; set; }
        [DisplayName("HASAR YERÝ")]
        public string HasarYeri { get; set; }

        public virtual Kitap Kitap { get; set; }
        public virtual Users Users { get; set; }
    }
}
