//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kutuphane.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbLibrarySomeeEntities1 : DbContext
    {
        public dbLibrarySomeeEntities1()
            : base("name=dbLibrarySomeeEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dil> Dil { get; set; }
        public virtual DbSet<EmanetKitaplar> EmanetKitaplar { get; set; }
        public virtual DbSet<Kategori> Kategori { get; set; }
        public virtual DbSet<Kitap> Kitap { get; set; }
        public virtual DbSet<KitapYazarlari> KitapYazarlari { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<YayinEvi> YayinEvi { get; set; }
        public virtual DbSet<Yazar> Yazar { get; set; }
        public virtual DbSet<ViewEmanetKitaplar> ViewEmanetKitaplar { get; set; }
    }
}
